spring.application.name=medical-clinic
// wyłączenie dokumentacji, pozwala nie udostęniać na zewnątrz szczegółów implementacyjnych w środowisku produkcyjnym

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true